# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    production:
      - step:
          name: Build
          image: node:14.18.0
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "ap-southeast-1"
                ACL: "public-read"
                S3_BUCKET: "metapet.icompx.com"
                LOCAL_PATH: $BITBUCKET_CLONE_DIR/dist # This is the base directory of your repository.
                #DELETE_FLAG: "true"